# Linear Regression

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(y_train)

tensor([[1.],
        [2.],
        [3.]])
tensor([[2.],
        [4.],
        [6.]])


In [3]:
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [4]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [5]:
H = x_train * W + b
print(H)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [6]:
cost = torch.mean((H - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [7]:
optimizer = optim.SGD([W, b], lr = 0.01)

In [8]:
# gradient를 0으로 초기화 -> 새로운 가중치 편향에 대해서 새로운 기울기를 구함
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

In [9]:
print(W)

tensor([0.1867], requires_grad=True)


In [10]:
epochs = 3000
for epoch in range(epochs):
    H = x_train * W + b
    cost = torch.mean((H-y_train) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 300 == 0:
        print("epoch: {:4d}/{} W: {:.3f}, b: {:.3f} cost: {:.6}".format(epoch, epochs, W.item(), b.item(), cost.item()))

epoch:    0/3000 W: 0.353, b: 0.151 cost: 14.771
epoch:  300/3000 W: 1.843, b: 0.356 cost: 0.0183056
epoch:  600/3000 W: 1.924, b: 0.173 cost: 0.00431935
epoch:  900/3000 W: 1.963, b: 0.084 cost: 0.00101919
epoch: 1200/3000 W: 1.982, b: 0.041 cost: 0.000240487
epoch: 1500/3000 W: 1.991, b: 0.020 cost: 5.67445e-05
epoch: 1800/3000 W: 1.996, b: 0.010 cost: 1.33891e-05
epoch: 2100/3000 W: 1.998, b: 0.005 cost: 3.15979e-06
epoch: 2400/3000 W: 1.999, b: 0.002 cost: 7.45942e-07
epoch: 2700/3000 W: 2.000, b: 0.001 cost: 1.76447e-07


# Multivariable Linear Regression

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [12]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [13]:
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [14]:
optimizer = optim.SGD([W, b], lr=1e-5)

In [15]:
epochs = 1000
for epoch in range(epochs):
    H = x_train.matmul(W) + b
    cost = torch.mean((H - y_train) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 300 == 0:
        print('Epoch {:4d}/{} H: {} Cost: {:.6f}'.format(epoch, epochs, H.squeeze().detach(), cost.item()))

Epoch    0/1000 H: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  300/1000 H: tensor([154.0120, 185.0385, 176.0329, 198.4569, 141.2353]) Cost: 5.281667
Epoch  600/1000 H: tensor([153.9632, 184.9662, 176.3143, 198.2966, 141.2586]) Cost: 4.652731
Epoch  900/1000 H: tensor([153.9126, 184.9032, 176.5724, 198.1471, 141.2855]) Cost: 4.107261


# nn.Linear

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [17]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [18]:
model = nn.Linear(1, 1)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [19]:
epochs = 1000
for epoch in range(epochs):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    0/1000 Cost: 23.906942
Epoch  100/1000 Cost: 0.145200
Epoch  200/1000 Cost: 0.089725
Epoch  300/1000 Cost: 0.055444
Epoch  400/1000 Cost: 0.034261
Epoch  500/1000 Cost: 0.021171
Epoch  600/1000 Cost: 0.013083
Epoch  700/1000 Cost: 0.008084
Epoch  800/1000 Cost: 0.004996
Epoch  900/1000 Cost: 0.003087


In [20]:
test = torch.FloatTensor([[4.0]])
y_hat = model(test)
print(y_hat)

tensor([[7.9124]], grad_fn=<AddmmBackward>)


# Class로 구현

In [21]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        
    def forward(self, x):
        return self.linear(x)

In [22]:
model = LinearRegression()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [23]:
epochs = 1000
for epoch in range(epochs):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    0/1000 Cost: 33.919323
Epoch  100/1000 Cost: 0.015275
Epoch  200/1000 Cost: 0.009439
Epoch  300/1000 Cost: 0.005833
Epoch  400/1000 Cost: 0.003604
Epoch  500/1000 Cost: 0.002227
Epoch  600/1000 Cost: 0.001376
Epoch  700/1000 Cost: 0.000850
Epoch  800/1000 Cost: 0.000526
Epoch  900/1000 Cost: 0.000325
